config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers:{
    sessions: 'users/sessions',
    regisrations: 'users/registrations'
  }
  get '/u/:id', to: 'users#profile', as: 'user'
  get 'users', to: 'users#index'
  
  # /jobs/1/comments/4
  resources :jobs do
    resource :comments
  end

  get 'home', to:'pages#home'
  get 'about', to:'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"


  
end

app/models/job.rb
class Job < ApplicationRecord
    validates :duedate, presence: true, length: {minimum: 5, maximum: 50}
    validates :job, presence: true, length: {minimum: 1, maximum: 1000}
    belongs_to :user
    #after_destroy {notify admin of bad behavior}
    has_many :comments, dependent: :destroy
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]
  skip_before_action :verify_authenticity_token
  

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
    @job.update(views: @job.views+1)
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user = current_user

    respond_to do |format|
      if @job.save
        format.html { redirect_to jobs_path, notice: t('notice.completed') }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  # to return to the job show use redirect_to job_url(@job)
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to jobs_path, notice: t('notice.updated') }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: t('notice.deleted') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:duedate, :department, :job, :status)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="container">
  <%= form_with(model: job) do |form| %>
    <% if job.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

        <ul>
          <% job.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="input-group mb-3">
      <%= form.label t('field.department'), style: "display: block", class:"input-group-text" %>
      <%= form.text_field :department, class:"form-control"%>
    </div>
    <div class="input-group mb-3">
      <%= form.label t('field.jobs'), style: "display: block", class:"input-group-text" %>
      <%= form.text_field :job, class:"form-control"%>
    </div>
    <div class="input-group mb-3">
      <%= form.label t('field.duedate'), style: "display: block", class:"input-group-text" %>
      <%= form.text_field :duedate, class:"form-control"%>
    </div>        
    <div class="input-group mb-3">
      <%= form.label t('field.status'), style: "display: block", class:"input-group-text" %>
      <%= form.text_field :status, class:"form-control"%>
    </div> 
    <div>
      <%= form.submit :OK, class:"btn btn-primary mt-3" %>
      <%= link_to t('page.jobs_list'), jobs_path, class:"btn btn-secondary mt-3" %>
    </div>
  <% end %>
</div>  

app/views/jobs/_job.html.erb
<table id="<%= dom_id job %>" class="table">
  <tr>
    <th><strong><%= t('field.department') %></strong></th>
    <td><%= job.department %></td>
  </tr>
  <tr>
    <th><strong><%= t('field.jobs') %></strong></th>
    <td><%= job.job %></td>
  </tr>
  <tr>
    <th><strong><%= t('field.duedate') %></strong></th>
    <td><%= job.duedate %></td>
  </tr>
  <tr>
    <th><strong><%= t('field.status') %></strong></th>
    <td><%= job.status %></td>
  </tr>

</table>

app/views/jobs/edit.html.erb
<div class="container">
  <h3><%= t('page.edit') %></h3>

  <%= render "form", job: @job %>

  <br>

  <div>
    <%= link_to t('page.target')+t('page.jobs'), @job %> |
    <%= link_to t('page.jobs_list'), jobs_path %>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container">
  <h1><%= t('page.jobs_list') %></h1>
  <% if user_signed_in? %>
  <%= link_to "新規", new_job_path %>
  <%end%>
  <table class="table table-striped" id="jobs">
    <thead class="table-dark">
      <tr>
        <th><%= t('field.name')%></th>
        <th><%= t('field.department')%></th>
        <th><%= t('field.jobs')%></th>
        <th><%= t('field.duedate')%></th>
        <th><%= t('field.status')%></th>
        <th><%= t('field.reviews_no')%></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @jobs.each do |job| %>
        <tr id="<%= dom_id job %>">
          <td>
            <%= job.user.name %>
          </td>
          <td>
            <%= job.department %>
          </td>
          <td>
            <%= link_to job.job, job %>
          </td>
          <td>
            <%= job.duedate %>
          </td>
          <td>
            <%= job.status %>
          </td>
          <td>
            <%= pluralize(job.views, "view") %>
          </td>
          <td>
              <% if user_signed_in? && current_user.name == job.user.name %>
                <%= link_to t('page.delete'), job_path(job), data: {turbo_method: :delete, turbo_confirm: "削除しますか？"}, class:"btn btn-danger" %>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/jobs/new.html.erb
<div class="container my-3">
  <h3><%= current_user.name+t('page.jobs')+t('page.new')+t('page.register') %></h3>
  <%= render "form", job: @job %>
</div>

app/views/jobs/show.html.erb
<div class="container mt-3">
  <h6><%= @job.user.name+t('page.jobs') %></h6>
  <%= render @job %>

  <div>
    <% if user_signed_in? && current_user.name == @job.user.name %>
      <%= link_to t('page.edit'), edit_job_path(@job), class:"btn btn-primary" %>
    <% end %>  
    <%= link_to t('page.jobs_list'), jobs_path, class:"btn btn-secondary" %>
  </div>
</div>
<!--
<br>
 <div class="container">
   <%= render 'comments/form', job: @job %>
 </div>
-->